/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CreateQueueMessage": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyPythonContainer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
