# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class CreateQueueMessage:
        name: str
        type: str
        url: str
    class MyPythonContainer:
        name: str
        type: str
        url: str
    class MyQueue:
        type: str
        url: str

